import("//build_overrides/chip.gni")

config("includes") {
  include_dirs = [ "." ]
}

source_set("oob-command") {
  sources = [
    "AllDevicesAppClusterImplementationRegistry.h",
    "AllDevicesAppNamedPipeCommandHandler.h",
    "AppCommandDelegate.cpp",
    "AppCommandDelegate.h",
    "ClusterTypeMappings.cpp",
  ]

  public_deps = [
    "${chip_root}/src/app/clusters/ambient-context-sensing-server",
    "${chip_root}/src/app/clusters/basic-information",
    "${chip_root}/src/app/clusters/boolean-state-server",
    "${chip_root}/src/app/clusters/electrical-energy-measurement-server",
    "${chip_root}/src/app/clusters/occupancy-sensor-server",
    "${chip_root}/src/app/clusters/on-off-server",
    "${chip_root}/src/lib",
    "${chip_root}/third_party/jsoncpp",
  ]

  public_configs = [
    ":includes",
    "${chip_root}/src:includes",
  ]
}
