# Copyright (c) 2026 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

assert(current_os == "win")

static_library("windows-system-primitives") {
  sources = [
    "WindowsClock.cpp",
    "WindowsClock.h",
    "WindowsMutex.h",
    "WindowsWakeEvent.cpp",
    "WindowsWakeEvent.h",
  ]

  deps = [ ":windows-system-errors" ]
  public_configs = [ ":public" ]
  libs = [ "Ws2_32.lib" ]
}

static_library("windows-system-errors") {
  sources = [
    "../SystemError.cpp",
    "../SystemError.h",
  ]

  deps = [ "//src/lib/core/windows:windows-core-portable" ]
  public_configs = [
    ":public",
    ":system-config",
  ]
}

static_library("windows-system-shared-compile") {
  sources = [
    "../../lib/support/TimeUtils.cpp",
    "../SystemClock.cpp",
    "../SystemClock.h",
    "../SystemConfig.h",
    "../SystemMutex.cpp",
    "../SystemMutex.h",
  ]

  deps = [
    ":windows-system-errors",
    ":windows-system-primitives",
    "//src/lib/core/windows:windows-core-portable",
  ]
  public_configs = [
    ":public",
    ":system-config",
  ]
}

static_library("windows-system-layer") {
  sources = [
    "../../lib/support/Pool.cpp",
    "../../lib/support/Pool.h",
    "../../lib/support/TimeUtils.cpp",
    "../SystemClock.cpp",
    "../SystemClock.h",
    "../SystemTimer.cpp",
    "../SystemTimer.h",
    "SystemLayerImplWindows.cpp",
    "SystemLayerImplWindows.h",
  ]

  deps = [
    ":windows-system-errors",
    ":windows-system-primitives",
    "//src/lib/core/windows:windows-core-portable",
  ]
  public_configs = [
    ":public",
    ":system-config",
  ]
}

config("system-config") {
  defines = [
    "CHIP_DEVICE_LAYER_USE_ATOMICS_FOR_CLOCK=0",
    "CHIP_AUTOMATION_LOGGING=0",
    "CHIP_DETAIL_LOGGING=0",
    "CHIP_ERROR_LOGGING=0",
    "CHIP_PROGRESS_LOGGING=0",
    "CHIP_SYSTEM_CONFIG_PLATFORM_PROVIDES_TIME=0",
    "CHIP_SYSTEM_CONFIG_USE_LWIP=0",
    "CHIP_SYSTEM_CONFIG_USE_NETWORK_FRAMEWORK=0",
    "CHIP_SYSTEM_CONFIG_USE_OPENTHREAD_ENDPOINT=0",
    "CHIP_SYSTEM_CONFIG_USE_POSIX_SOCKETS=0",
    "CHIP_SYSTEM_CONFIG_USE_POSIX_TIME_FUNCTS=0",
    "CHIP_SYSTEM_CONFIG_USE_SOCKETS=1",
    "INET_CONFIG_ENABLE_TCP_ENDPOINT=1",
    "INET_CONFIG_ENABLE_UDP_ENDPOINT=1",
    "INET_CONFIG_NUM_TCP_ENDPOINTS=4",
    "INET_CONFIG_NUM_UDP_ENDPOINTS=4",
  ]
}

config("public") {
  include_dirs = [
    "//src",
    "//src/include",
  ]
}
